version: '3'

services:
  app:
    build: .
    container_name: video-auth-app
    entrypoint: /opt/jboss/keycloak/bin/entrypoint.sh
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT_MULTI=/opt/jboss/keycloak/realm-config
      - DB_ADDR=db
      - DB_VENDOR=mysql
      - DB_DATABASE=video_auth
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - 8080:8080
    volumes:
      - ./.docker/keycloak/entrypoint.sh:/opt/jboss/keycloak/bin/entrypoint.sh
      - ./.docker/keycloak/realm-config:/opt/jboss/keycloak/realm-config
      - ./frontend/build/video-catalog-admin:/opt/jboss/keycloak/themes/video-catalog-admin
      - ./.docker/keycloak/config/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
    depends_on:
      - db
    networks:
      default:
        aliases:
          - app.test

  db:
    build: ./.docker/mysql
    container_name: video-auth-db
    restart: always
    tty: true
    ports:
      - 33306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=video_auth
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - default

  frontend:
    build: ./frontend
    entrypoint: ./.docker/entrypoint.sh
    container_name: video-auth-frontend
    volumes:
      - ./frontend:/home/node/app
    networks:
      - default

  test:
    build: ./tests
    entrypoint: ./.docker/entrypoint.sh
    container_name: video-auth-test
    volumes:
      - ./tests:/home/node/app
    networks:
      - default

  selenium:
    image: selenium/standalone-chrome:88.0.4324.150-chromedriver-88.0.4324.96
    container_name: micro-auth-selenium
    expose:
      - 4444
    networks:
      - default

networks:
  default:
    driver: bridge

