version: '3'

services:
  app:
    build: .
    container_name: 'video-auth-app'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=db
      - DB_VENDOR=mysql
      - DB_DATABASE=video_auth
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - 8080:8080
    volumes:
      - ./frontend/build/video-catalog-admin:/opt/jboss/keycloak/themes/video-catalog-admin
      - ./.docker/keycloak/config/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
    depends_on:
      - db

  db:
    build: ./.docker/mysql
    container_name: video-auth-db
    restart: always
    tty: true
    ports:
      - 33306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=video_auth
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root

  frontend:
    build: ./frontend
    entrypoint: ./.docker/entrypoint.sh
    container_name: video-auth-frontend
    volumes:
      - ./frontend:/home/node/app